### ISSUE TITLE
ObterTracking Call returning the same value

### ISSUE THREAD

**Issue by fjcunha** [rodcorporation/TotalExpressWSClient#1]
When using the method TotalExpressWS.ObterTracking(), the count and structure of the result is right but is duplicating the first value multiple times on response payload

**Comment by fjcunha** [comment]
I found the problem in response Binding method ( TotalExpressWSClient.ObterTracking.ObterTrackingResponseBinding() ), on translate the xml to object.

When you loop through the domain elements under the domains parent, you shouldn't again use // - that will reset the context to the root of the document.

**Comment by fjcunha** [comment]
I'm working on a PR to fix it

**Comment by rodcorporation** [comment]
Thank you Fabricio. I'm waiting for you PR.
